server:
  port: 8081

spring:
  application:
    name: avgeek-admin-telegram-bot

  jpa:
    hibernate:
      ddl-auto: none

  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

bot:
  name: ${BOT_NAME}
  token: ${BOT_TOKEN}
  creator-id: ${BOT_CREATOR_ID}
