server:
  port: 8081

spring:
  application:
    name: avgeek-admin-telegram-bot

  jpa:
    hibernate:
      ddl-auto: none

  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

  data:
    mongodb:
      host: ${MONGO_HOST}
      port: ${MONGO_PORT}
      database: ${MONGO_DATABASE}
      username: ${MONGO_USERNAME}
      password: ${MONGO_PASSWORD}
      authentication-database: admin

bot:
  name: ${BOT_NAME}
  token: ${BOT_TOKEN}
  creator-id: ${BOT_CREATOR_ID}

github:
  base-url: https://api.github.com/repos/
  access-token: ${GITHUB_ACCESS_TOKEN}
  username: ${GITHUB_USERNAME}
  repository-name: ${REPOSITORY_NAME}
